rollingpin/frontends.py, rollingpin/log.py
This prevents a crash when there's non-ASCII stuff in the logs. For
example, stuff like "65 μs".
(This was particularly noticeable in mweb deploys)
:eyeglasses: @dellis23 @Deimos
=> Decode UTF8 in log formatters

example.ini, rollingpin/deploy.py, rollingpin/frontends.py, rollingpin/hostsources/__init__.py, rollingpin/hostsources/autoscaler.py, rollingpin/hostsources/mock.py, rollingpin/main.py, rollingpin/transports/mock.py
This is the first phase of moving to hippo deploys. Instead of passing around a hostname as a string everywhere, we pass around host objects. These allow us to carry more info about the host. Then this allows us to use the IP address from the autoscaler inventory instead of relying on DNS. This removes the dependency on legacy DNS for deploys and should help get rollout in touch with boxes that are in the waitingdns state.
:eyeglasses: @dellis23 @ckwang8128
=> Pass a host object around instead of just a string; use that to avoid DNS

rollingpin/hostsources/hippo.py
These logging calls aren't terribly helpful outside of development but
since they're made so early on in the app startup, they're causing an
extra StreamHandler to get automatically created. This ends up making
every log statement later on in the app doubled; once through the
automatically made and defaultly styled handler, and once through our
colorized and fancy one. Removing the logging calls makes this safe.
:eyeglasses: @bsimpson63 @dellis23
=> Remove unneeded logging calls that cause extraneous handler

rollingpin/elasticsearch.py, rollingpin/main.py, tests/elasticsearch.py
Now that we have metadata being dispatched to ES, lets start sending more deploy metadata to elasticsearch
=> Add additional metadata about deploys to ES, Don't split docs on multiple components

rollingpin/elasticsearch.py, tests/elasticsearch.py
Our current version of Grafana does not support elasticsearch
timetamps to be in seconds. Need to convert them into milliseconds
before sending them off. Also correlate deploy end events with the service
so we can filter them easily in Grafana
=> ES timestamp in milliseconds, send more info on abort, end events

rollingpin/hostsources/mock.py
👓 @spladug @foklepoint 
I don't know if this is the actual solution we want, but right now the gangplank server can't deploy without this commit hotpatched in, and I didn't want to just leave it around.  Alternatively, should we just have a host source that is for a static list of hosts?  Or is there enough of an overlap with the mock host source that it'd be unnecessary?
=> Don't append local to mock addresses.

README.md, example-deploy.py, rollingpin/deploy.py, rollingpin/frontends.py, setup.cfg, tests/frontends.py
👓  @spladug @foklepoint 
Right now, the component report must be explicitly passed by the operator.  I think this makes things a lot cleaner so we don't have to inject the command in and gracefully handle when the deploy script doesn't support component reports.  My thinking is that we can look at making this happen every time later on if we find it useful.  This also obviates the need to be "smart" about the short format (i.e. don't show output if it looks like only one SHA is running per component), since the operator will have explicitly requested a report.  We can still do the smart thing if we make it required, but I want to makes sure it's clear when the component report is failing versus everything being okay (since both would seemingly result in no output under the smart case).
I …
=> Add Component Report

rollingpin/frontends.py
This fixes #10 and a case we saw with desktop2x (which has exactly 14 servers) where deploying to 10% would unleash the deploy but deploying to e.g. 15% would not.
=> Fix percent rollout edge cases

example_profile.ini, rollingpin/args.py, rollingpin/elasticsearch.py, rollingpin/main.py, tests/args.py
Attempt to fulfill the desire for rollingpin to be aware and contextually configurable for multiple projects.  Before the internal configuration was global and the same across different project deploys.  This adds a required argument that defines a "profile" which ends up being an additional configuration file to be loaded and can provide more defaults to dictate a sane default behavior based on a profile.  Because of how the configuration loading is done, *any* config value that works in the global config can be overridden via the profile configuration.
For example, `$ rollout -h apps -d public -r all` could become `$ rollout public` where the `public` profile would be an ini file that sets defaults for the three argumented flags.
Currently (like the location of the global and user …
=> Profile support for rollingpin

rollingpin/deploy.py, rollingpin/frontends.py, rollingpin/main.py, rollingpin/status.py
This checks against a new endpoint in Harold to see if it's currently
outside of sanctioned deploy times or other deploys are in progress and
displays a warning prompt to the user if either condition applies. This
is intended to give a little extra indication that extra consideration
should be applied and not a hard rule.
We'll want to only land this after @jdost's project profile thing as currently
all the backend projects are sharing a harold improperly.
Feel free to bikeshed wording, I tried to go for "admonishment without being too judgy" and didn't want to get too specific on our policies since this is a general tool.
Here's the relevant harold commit if curious: https://github.com/spladug/harold/commit/9c838a94ca588afb1e731e731760484ed4f18cb5
=> Prompt users with warnings if deploying in unsafe conditions

rollingpin/frontends.py, rollingpin/status.py
Relevant harold changes are [here](https://github.com/spladug/harold/compare/hold-status). I'll roll this out first since then rollout will start sending authentication headers (and will safely ignore a missing hold status in response). Then I'll deploy the harold change to require the authentication and add hold status.
=> Add hold status to pre-deploy checks

rollingpin/main.py
This makes it so we interleave hosts from different aliases instead of
clumping them all together in alias order. This ensures wider spreading
of small host groups that have different prefixes, like job servers.
=> Interleave hosts by pool after alias resolution

example.ini, rollingpin/frontends.py, rollingpin/harold.py, rollingpin/transports/mock.py
This lets us alert on them instead of bugging users and relying on them
to report it when necessary.
There are also a few fixes to local testing here broken out into separate commits.
=>  Report failed hosts during deploys to harold rather than user

rollingpin/transports/ssh.py
👓  @spladug 
Sorry it took me a bit on this, was caught up in other things.  I haven't tested this yet -- still need to come up with a reproducible case locally since this wasn't happening for me in the case of a timeout.  Obviously I won't ship this unless I can get the failure working consistently and prove this fixes it.
=> Fix AlreadyCalledError in case of timeout.

rollingpin/frontends.py
This was causing crashes during deploys. I'm still not sure why it's
happening but this should be safe to do.
This is the patch I hacked up on tools yesterday to unblock a deploy. I'd
like to get it out today so no one gets stuck during an emergency over the
weekend.
=> Guard against host_end/host_abort happening twice

example_profile.ini, rollingpin/harold.py, rollingpin/main.py, rollingpin/status.py
This allows a single harold instance to figure out which salon a deploy
is managed by.
=> Send salon name in harold requests

rollingpin/hostsources/hippo.py
Recently r2 moved from numbered "app-*" names
to "r2-app" and now sets a Hostclass, so the
Hostclass + instance-ID naming scheme should
now be propagated to all services and can
be the rollingpin default for the Hippo hostsource.
:eyeglasses: @alienth @spladug
=> Swap Hippo Host name lookups

rollingpin/main.py
:eyeglasses: @spladug @ckwang8128 
I've had to do this indirectly many times, so getting it directly would be handy.
Main concern would be if we have existing scripts which depend upon the output of `--list`.
=> Print host address when `list`ing.

example.ini, rollingpin/elasticsearch.py, rollingpin/main.py, rollingpin/utils.py, rollingpin/wavefront.py, tests/wavefront.py
This adds [Wavefront Event](https://docs.wavefront.com/events.html) creation functionality to the Rollingpin deploy process. One Event is created per deploy, with Event closing happening on finished or aborted deploys. Deploy name information is provided in details, and the deploy profile is captured in the name of the event. 
:eyeglasses: @spladug @foklepoint
=> Wavefront annotations

example.ini, rollingpin/args.py, rollingpin/commands.py, rollingpin/deploy.py, rollingpin/transports/mock.py, tests/args.py
essentially:
* The deploy stage can now return a dictionary of
```{
"component@hash": true/false,
....
}
```
Determining whether or not that component is safe to skip a restart for.
* If all components have the false bit set, we skip the remaining commands for that host, which will be the restart and wait-for-components commands.
I did a little bit of refactoring for this to avoid dumping more conditional logic into deploy.py --
* I replaced the use of ["command", "args"...] lists with command objects where deploy lifecycle logic can be defined. I'm not super married to this refactor as it doesn't really buy too much right now, but the pattern seems to feel to feel a bit better now that we're starting to add more conditional logic to the deploy flow.
* generalized the mock transport a bit …
=> Skip restart if deploy script reports no code changes

rollingpin/transports/ssh.py
After upgrading twisted we're observing failures in prod where no
functions have been called setting `state`.
:eyeglasses: @eaceaser @spladug
=> Initialize factory.state.

rollingpin/wavefront.py, tests/wavefront.py
Add generic deploy tag. We want to be able to search the 'deploy' tag in wavefront and see all deploy events.
=> Add generic deploy tag

rollingpin/harold.py, rollingpin/status.py
adds a 5 second timeout to harold requests.
When the status API times out (this behavior already existed):
>failed to fetch deploy status: timed out 
When the harold progress event times out (this is new timeout behavior):
> harold: request timed out after 5 seconds (/harold/deploy/progress)
=> Add harold timeout
